describe('Map', function()
    it('can be loaded from file')
    it('can be saved to file')
    it('allows getting and setting position of tile/character')
    it('allows getting and setting tile/character at position')
end)
