describe('state', function()

    local state = require('state')
    before_each(function()
        state:init()
    end)

    it('is empty to begin with', function()
        assert.is_nil(state:current())
    end)

    it('can be pushed to', function()
        state:push('dummy1')
        assert.is_equal(state:current(), 'dummy1')
        state:push('dummy2')
        assert.is_equal(state:current(), 'dummy2')
    end)

    it('can be poped from', function()
        state:push('dummy1')
        state:push('dummy2')
        state:pop()
        assert.is_equal(state:current(), 'dummy1')
        state:pop()
        assert.is_nil(state:current())
    end)

    it('can be emptied', function()
        state:push('dummy1')
        state:push('dummy2')
        state:empty()
        assert.is_nil(state:current())
    end)
end)
